###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '30001:8025'

  redis:
    image: 'redis:alpine'

  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=regexp
    volumes:
      - './phpdocker/psql:/var/lib/postgresql/data'
    ports:
      - '30004:5432'

  adminer:
    image: adminer
    ports:
      - 8080:8080

  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '30000:80'

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
